name: univalle_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  dio_cookie_manager: ^3.2.0
  cookie_jar: ^4.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.0
  html: ^0.15.5
  flutter_svg: ^2.0.17
  shared_preferences: ^2.5.2
  webview_flutter: ^4.10.0
  barcode_widget: ^2.0.4
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/svg/