abstract final class AppRoutes {
  static const home = '/';
  static const login = '/login';
  static const profile = '/profile';
  static const forgotPassword = '/forgot-password';
  static const grades = '/grades';
  static const digitalCard = '/digital-card';
  static const tabulate = '/tabulated';
  static const resolution = '/resolution';
  static const teacherRating = '/teacher-rating';
  static const teacherReview = '/teacher-rating/review';
  static const schedule = '/schedule';
  static const restaurant = '/restaurant';
  static const library = '/library';
  static const news = '/news';
  static const announcements = '/announcements';
  static const pendingPayment = '/restaurant/pending-payment';
  static const allFunctionalities = '/functionalities';
}
